### PR TITLE
dependence version updated

### PR DESCRIPTION
**Pull request by ars27196**
Readme file was updated to add a current version number of the lib.

### CODE REVIEW

**Comment by mehdizarepour** [comment]
Hi @ars27196,

Thank you for opening this PR, Could you please ignore your changes on the `.packages` file?

**Review by mehdizarepour — CHANGES_REQUESTED** [review]
Please ignore changes on the `.packages` file.

**Comment by ars27196** [comment]
Please update the lib page on pub.dev.

**Comment by ars27196** [comment]
Hi, Would you be open to more changes in this library? The JS lib, load dash, also supports lists (arrays). I was thinking maybe we can add support for that. Thanks

**Comment by mehdizarepour** [comment]
@ars27196 Thank you for the changes.

>Would you be open to more changes in this library? 

Yes of course you are welcome to PR.

**Pull request merged**
